<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [43]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [44]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

##### Creating a 1 D array of ones

In [45]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [46]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [47]:
arr = np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [48]:
arr.dtype

dtype('int64')

##### Creating a 5  x 3 array of ones


In [49]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### Creating array of zeros

In [50]:
np.zeros((5,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [52]:
# Create a list of integers range between 1 to 5.
list(range(1,5))

[1, 2, 3, 4]

In [53]:
np.arange(3)

array([0, 1, 2])

In [54]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [55]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [56]:
np.random.randint(2, size=10)

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [57]:
np.random.randint(3,5, size=10)

array([4, 4, 4, 4, 3, 3, 3, 4, 4, 3])

##### 2D Array of random numbers 


In [58]:
np.random.random([5,4])

array([[0.10874752, 0.80150077, 0.10885119, 0.08752005],
       [0.52360823, 0.79667609, 0.99856463, 0.09150405],
       [0.2180912 , 0.95676862, 0.15003446, 0.2247857 ],
       [0.33649642, 0.0833901 , 0.24241232, 0.32841046],
       [0.38724909, 0.17299921, 0.88302154, 0.21725794]])

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [59]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [60]:
np.full(3,2)

array([2, 2, 2])

In [61]:
np.tile(5,7)

array([5, 5, 5, 5, 5, 5, 5])

In [62]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.random.randint(2,6,2)

array([4, 2])

In [64]:
np.random.random([0,0])

array([], shape=(0, 0), dtype=float64)

In [67]:
n = 5
border_array = np.ones((n, n), dtype = int)
border_array[1:-1, 1:-1] = 0

In [68]:
print(border_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
